name: Local MLflow CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Install flake8 for linting
        run: pip install flake8

      - name: Run linting
        run: flake8 src/  # Lint your source code

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest  # Run your unit tests

  train_and_log_model:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      - name: Pull data from DVC
        run: |
          # Make sure to configure DVC remote if needed (skip if already configured)
          dvc pull

      - name: Train model and log with MLflow
        run: |
          python src/train.py
          
  deploy_model:
    runs-on: ubuntu-latest
    needs: train_and_log_model
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy the trained model
        run: |
          python src/deploy_model.py
